name: Run Tests

on:
  push:
    branches: ['*']

jobs:
  tests:
    name: jest-tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run ci-test
